name: Nextview Developments
favicon: null
layout_spectrum: 0.2466393185313791
typography_spectrum: 0.8333586687222123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7546389074996114
  lightness: 0.7448033441323787
  saturation: 0.8814724292606115
  rhythmicContrast: 0.30397555069066584
purpose: []
