name: Nextview Developments
favicon: null
layout_spectrum: 0.2466393185313791
typography_spectrum: 0.8333586687222123
title: Nextview Developments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#2f93ef'
    - '#166cbb'
    - '#1e79cc'
    - '#000000'
  brandStrength: 0.7546389074996114
  lightness: 0.7448033441323787
  saturation: 0.8814724292606115
  rhythmicContrast: 0.30397555069066584
purpose: []
